### ISSUE TITLE
Mysterium #1

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#125]
Folder: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/January/progressed/myst/mysterium1

empty-content: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/myst/mysterium1/empty_new.html

template:  https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/myst/mysterium1/template_new.html

строки в которые нужно добавить контент:
- https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template.html#L502
- https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template.html#L532
- https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template.html#L562
- https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template.html#L592
- https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template.html#L622

PDF with the current version of content: 
[VPNs Leaked 1.2TB of Your Data_ Who Can You Trust_.pdf](https://github.com/atherdon/newsletters/files/5836865/VPNs.Leaked.1.2TB.of.Your.Data_.Who.Can.You.Trust_.pdf)

**Comment by atherdon** [comment]
нужно добавить title: 
**VPNs Leaked 1.2TB of Your Data: Who Can You Even Trust?**


https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template_new.html#L18

**Comment by F1reMonster** [comment]
> нужно добавить title:
> **VPNs Leaked 1.2TB of Your Data: Who Can You Even Trust?**
> 
> https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/January/progressed/mysterium1/template_new.html#L18

готово

**Comment by atherdon** [comment]
пока нету данных от клиента насчет ссылок и рекламы - эта задача готова

**Comment by atherdon** [comment]
Ad copy: **MYST is now on Bittrex**
Link: https://bit.ly/3bSndkj
logo: https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/logos/thematic/2021/January/28.10/Mysterium.png

**Comment by atherdon** [comment]
[VPNs Leaked 1.2TB of Your Data_ Who Can You Trust_.pdf](https://github.com/atherdon/newsletters/files/5888429/VPNs.Leaked.1.2TB.of.Your.Data_.Who.Can.You.Trust_.pdf)

**Comment by F1reMonster** [comment]
> Ad copy: **MYST is now on Bittrex**
> Link: https://bit.ly/3bSndkj
> logo: https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/logos/thematic/2021/January/28.10/Mysterium.png

done

**Comment by atherdon** [comment]
готово
