### ISSUE TITLE
webny 2

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#142]
[Newsletter Web #2_ The Ugly Truth About Serverless Data Security.pdf](https://github.com/atherdon/newsletters/files/5905015/Newsletter.Webiny.2_.The.Ugly.Truth.About.Serverless.Data.Security.pdf)

Folder:  https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/Februrary/progressed/Webiny2

template: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/Februrary/progressed/Webiny2/template.html

Bitly: missing yet

**Comment by F1reMonster** [comment]
done

**Comment by atherdon** [comment]
нужно добавить ad message о котором все забыли :(


![image](https://user-images.githubusercontent.com/1469198/106515864-f15f3d00-64de-11eb-8d5d-9cff91baae85.png)

контент я перенес в этот файл: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/Februrary/progressed/Webiny2/adv.html

а bitly ссылка: https://bit.ly/3sDQOUK

**Comment by F1reMonster** [comment]
> нужно добавить ad message о котором все забыли :(
> 
> ![image](https://user-images.githubusercontent.com/1469198/106515864-f15f3d00-64de-11eb-8d5d-9cff91baae85.png)
> 
> контент я перенес в этот файл: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/Februrary/progressed/Webiny2/adv.html
> 
> bitly ссылка: https://bit.ly/3sDQOUK
> Ad Copy: "The easiest way to adopt serverless"
> 
> we also need to add this link: https://hackernoon.com/when-youre-blocked-online-can-you-just-diy-your-own-internet-6jm32vr
> 
> for "ultimate user experience"
> 
> ![image](https://user-images.githubusercontent.com/1469198/106610387-69754380-656f-11eb-9136-3688a98efddf.png)

done
