### ISSUE TITLE
create empty folders & files and clean template for upcoming campaigns

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#149]
Если я правильно понял, то у нас устаканился план по новым рассылкам на близжайшие несколько недель.
это поможет нам лучше планировать нашу работу и загруженость и может быть мы даже сможем заранее делать HTML темплейты для рассылки.

сегодня у нас будет очередная рассылка(и завтра поидее тоже): но детали я опишу немного позже.

вначале мы можем сделать подготовительную работу и создать пустые папки, файлы и чистый темплейт с пустыми тегами для основного контента(как мы делали в прошлый раз)
Список кампаний которые нам предстоят в феврале:
- webiny3
- bridgecrew1
- bridgecrew2
- webiny4
- launchdarkly1
- launchdarkly2
- Particle1
- Particle2
- Mysterium3
- mysterium4

**Comment by F1reMonster** [comment]
виконано

**Comment by atherdon** [comment]
closing
