### ISSUE TITLE
create ama template

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#157]
data from https://trello.com/c/irb9HOTx/10-build-ama-email-for-sesjust-in-case

1. fork this repository
2. get familiar with the current directory structure for each separate newsletter/campaign
3. create an empty folder on your forked repository with readme.md file with some content inside.
4. make a pull request with your changes, because I need to know that you can do PRs and code sync between repositories
5. open other empty folders with upcoming campaigns and copy(intelligently :)) those files into our separate folder
6. make a pull request
6.1. sync your branch
7. ask me about images
8. ask me about content
8.1. sync your branch
9. upload images on gitlab and provide links to raw image files. upload those paths to this repository via pull request
10. sync your branch
....
more coming

**Comment by atherdon** [comment]
@mikhailnathanielabordo feel free to post your current progress here.
it might help us to organize everything.

**Comment by atherdon** [comment]
Slogging template for ama(Sendy version) feedback - #159 

- we have different wrappers for content(text, links, images), this is why I'm building a generator - so we wouldn't need to keep track - and can just focus on content production.
- images/memes usually should be 220px max - otherwise, it will look ugly on mobile.
- footer is not the same.

My proposal:
- create a separate file, we can call it template_new.html. And you can grab an empty version of HTML template from other folders that we have in "/progressed"
- submit PR
- ask me to use a generator and create the markup for our email body.
- you can also upload meme image into a new folder at https://gitlab.com/hackernoon/creative/-/tree/master/newsletters/memes/2021/
and then I'll show you how to copy the raw path to it. when you'll create PR for that repo - please notify me, because I'm using David`s account.

**Comment by mikhailnathanielabordo** [comment]
> * footer is not the same.

the footer is intentional I think? it was requested by limarc. here is the reference: https://docs.google.com/document/d/15UyB0M8U9qHk64WI-xUlWAnSaCPboe3twV6anWB5H90/edit

noted on other things.

**Comment by atherdon** [comment]
> > * footer is not the same.
> 
> the footer is intentional I think? it was requested by limarc. here is the reference: https://docs.google.com/document/d/15UyB0M8U9qHk64WI-xUlWAnSaCPboe3twV6anWB5H90/edit
> 
> noted on other things.

I'm fine to have that footer on Sendgrid - but with Sendy we still using current footer. it will require a lot of chats and approvals in order to make footer changes :)

**Comment by mikhailnathanielabordo** [comment]
@atherdon I update the AMA Template. 🙇 here is the PR. https://github.com/atherdon/newsletters/pull/162

**Comment by atherdon** [comment]
i like it. the only thing - we need to move images from your repo into main repo on gitlab

**Comment by mikhailnathanielabordo** [comment]
> i like it. the only thing - we need to move images from your repo into main repo on gitlab

ohh. yeah. still figuring out how to merge my repo to your repo and vice versa in gitlab. 🤣 but sure will update that one. thanks.

**Comment by atherdon** [comment]
About links to images - can you push a pull request to https://gitlab.com/hackernoon/creative, please?

**Comment by atherdon** [comment]
I see your pull request. again - as main account was registered on David - I didn't get a notification about pull requests on gitlab

**Comment by atherdon** [comment]
but you just closed it :(

**Comment by mikhailnathanielabordo** [comment]
ahh. I thought wrong button. 😓

**Comment by atherdon** [comment]
ahha. dont worry - we'll handle that - all is fine

**Comment by mikhailnathanielabordo** [comment]
https://gitlab.com/hackernoon/creative/-/merge_requests/3

**Comment by atherdon** [comment]
@mikhailnathanielabordo merged, please update the path in our current newsletter template

**Comment by mikhailnathanielabordo** [comment]
https://github.com/atherdon/newsletters/pull/163

**Comment by mikhailnathanielabordo** [comment]
moved this to completed https://github.com/atherdon/newsletters/pull/171
cc: @atherdon

**Comment by mikhailnathanielabordo** [comment]
closing this as well. 🙇
