### ISSUE TITLE
lets organize 2019 archive

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#168]
this is how our current folder looks like:https://github.com/atherdon/newsletters/tree/master/archive/Thematic/archive/2019

and I propose to do few pull requests, with some changes. not like 1 pull request with everything inside o it :)

**Comment by atherdon** [comment]
cc @mikhailnathanielabordo

**Comment by mikhailnathanielabordo** [comment]
@atherdon here are some questions for this issue.

- Should we organize them by Month?
- Should we organize them by Company?
- Do we still need to create .md file?
- Some templates don't have dates where should that go?
- for creating PR, can it be just 1 PR with multiple commits? I think that's cleaner.

**Comment by atherdon** [comment]
let's organize them by dates? most of those templates just an export from Mailchimp.
we don't need to create md files for those files right now.

I'll prefer 1 pull request with 2 folder and few newsletters inside - it will help me to review your PRs much quicker and easy

**Comment by mikhailnathanielabordo** [comment]
Here are the re-organized repos

- https://github.com/atherdon/newsletters/pull/173
- https://github.com/atherdon/newsletters/pull/174
- https://github.com/atherdon/newsletters/pull/175

**Comment by atherdon** [comment]
@mikhailnathanielabordo can we close it?

**Comment by mikhailnathanielabordo** [comment]
yes. I think it's done already. I just don't have the access to close it myself. :)

**Comment by atherdon** [comment]
It's actually strange. I added you as contributor to this repository few days ago.
but I still cant assign tasks to you.. will attack this problem later.

closing then
