### ISSUE TITLE
move out bridgecrew2 campaing from progressing into completed

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#169]
cc @mikhailnathanielabordo

**Comment by mikhailnathanielabordo** [comment]
moved to completed https://github.com/atherdon/newsletters/pull/170

I don't have write access to fix the conflict file.

**Comment by atherdon** [comment]
hmm... let me take a look then. But its a great example of why to make a sync

**Comment by atherdon** [comment]
Closing it, because it's done
