### ISSUE TITLE
nba podcast

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#177]
Folder: feel free to copy all default files that we use

content: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/Februrary/progressed/nba/content.md

empty content: you can use my generator and create it automatically. Please don't do HTML by hands - it's scary for me.

cmpgn: https://www.noonifications.tech/edit?i=1&c=76

**Comment by atherdon** [comment]
@mikhailnathanielabordo I moved content into content.md file.
But we have a problem - it was copied from our Medium newsletter and all normal links replaced with their tracking links.
Can you open all those links and replace with real one, please?

**Comment by mikhailnathanielabordo** [comment]
sure. will check on that.

**Comment by mikhailnathanielabordo** [comment]
PR: https://github.com/atherdon/newsletters/pull/180

**Comment by atherdon** [comment]
merged. Will review full template a bit later. Probably we need to set a date and release it when we'll have some free spot between our newsletters

**Comment by mikhailnathanielabordo** [comment]
there are still some parts missing for this template like the bitly, ads, and logo. :)

for now just update the empty template so we can reference the changes later for review. :)

**Comment by atherdon** [comment]
for this newsletter - we wouldnt have an advertiser.
you can use the same template that we have for AMA.

**Comment by atherdon** [comment]
What do you think - should we put some images inside. I mean without pictures - is it not boring in your opinion?

**Comment by mikhailnathanielabordo** [comment]
> What do you think - should we put some images inside. I mean without pictures - is it not boring in your opinion?

yes we can. but I'm not actually sure what to add myself. 😅

**Comment by atherdon** [comment]
probably we can just add featured image with a ball that David choose for the featured image

**Comment by mikhailnathanielabordo** [comment]
Adding Image for NBA. I just get the Image of their book instead. https://gitlab.com/hackernoon/creative/-/merge_requests/7

here is the [reference](https://www.amazon.com/Bubbleball-Inside-NBAs-Fight-Season/dp/1419755536?&linkCode=sl1&tag=artmapincdbah-20&linkId=d97955373324ba2efdf60c7550df4c5f&language=en_US&ref_=as_li_ss_tl).

cc: @atherdon

**Comment by atherdon** [comment]
very smart idea!

**Comment by atherdon** [comment]
PR merged

**Comment by mikhailnathanielabordo** [comment]
@atherdon I create a campaign for this. not sure when should this be sent though. no details in [notion](https://www.notion.so/hackernoon/NBA-Book-Podcast-f38287b1b5c442f3a044dcd324939885).

**Comment by atherdon** [comment]
@mikhailnathanielabordo yep - because I didnt set a date yet.
I think we can try to send tomorrow a newsletter for Velo Contest. Then we'll have LaunchDarkly2 and maybe after that we can release NBA podcast letter
