### ISSUE TITLE
particle.io 1

### ISSUE THREAD

**Issue by mikhailnathanielabordo** [atherdon/newsletters#187]
Folder: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/Februrary/progressed/Particle1

empty content: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/Februrary/progressed/Particle1/empty.html

images(not moved): https://gitlab.com/hackernoon/creative/-/tree/master/newsletters/memes/2021/Feb/23.02

Bitly Link: https://bit.ly/3aAy2Ff

AD Copy: Free 1-day Master Class in IoT

Logo: https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/logos/thematic/2021/02-February/23.02/partcicle.png
cmpgn: https://www.noonifications.tech/edit?i=1&c=75

**Comment by mikhailnathanielabordo** [comment]
@atherdon can you merge this images? 🙇  https://gitlab.com/hackernoon/creative/-/merge_requests/8

**Comment by mikhailnathanielabordo** [comment]
also. here is the PR for the template. 🙇  https://github.com/atherdon/newsletters/pull/188

**Comment by atherdon** [comment]
Merged both PRs

**Comment by atherdon** [comment]
we need to change title to-  **IoT: Beyond Light Bulbs and Alexa**

and we will need to apply links into our newsletter when they will be done

**Comment by mikhailnathanielabordo** [comment]
changed the title here. https://github.com/atherdon/newsletters/pull/189

**Comment by mikhailnathanielabordo** [comment]
links updated. https://github.com/atherdon/newsletters/pull/190 cc: @atherdon

**Comment by atherdon** [comment]
merged @mikhailnathanielabordo

**Comment by mikhailnathanielabordo** [comment]
just notice that there are new lines added. https://github.com/atherdon/newsletters/pull/191 can you approve again? cc: @atherdon 🙇

**Comment by mikhailnathanielabordo** [comment]
closing this. 🙇
