### ISSUE TITLE
LaunchDarkly #2

### ISSUE THREAD

**Issue by mikhailnathanielabordo** [atherdon/newsletters#193]
Folder: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/Februrary/progressed/launchdarkly2

empty content: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2021/Februrary/progressed/launchdarkly2/empty.html

images: {Gitlab /memes/ folder}

Bitly Link: http://bit.ly/2NfWMeC

AD Copy: Get a FREE Copy of "Progressive Delivery"

AD Plug: What if you could "safely" ship software faster? Make speed a habit and learn how your team can reap the rewards of CI/CD without all of the risk. Download your copy of 'Progressive Delivery' and learn what elite software teams have in common, today!

Logo: {gitlab /logo/ folder}

cmpgn: {Noonifications: Available if all html templates are ready}

Trello: https://trello.com/c/cDgWHKhN/32-buidl-launchdarkyl-2-newsletter

**Comment by atherdon** [comment]
me trying to not include google docs here, for security reasons

>

**Comment by atherdon** [comment]
but thanks for keeping track on it

**Comment by mikhailnathanielabordo** [comment]
ahh. I see. I'll just move this to trello then include it there. 🙇

**Comment by mikhailnathanielabordo** [comment]
PR: https://github.com/atherdon/newsletters/pull/195
Image: https://gitlab.com/hackernoon/creative/-/merge_requests/9

cc: @atherdon

**Comment by atherdon** [comment]
merged both PRs @mikhailnathanielabordo

**Comment by mikhailnathanielabordo** [comment]
This was sent last friday. https://www.noonifications.tech/report?i=1&c=74 closing this now. 🙇
