### ISSUE TITLE
Webiny #4

### ISSUE THREAD

**Issue by mikhailnathanielabordo** [atherdon/newsletters#199]
Folder: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/March/progressed/webiny4

empty content:https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/March/progressed/webiny4/empty.html

images: https://gitlab.com/hackernoon/creative/-/tree/master/newsletters/memes/2021/03-March/01.03/

Bitly Link: https://bit.ly/3sDQOUK

AD Copy: Discover the new serverless CMS

Logo: https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/logos/thematic/2021/January/18.10/Webiny_logo_square.png

cmpgn: https://www.noonifications.tech/edit?i=1&c=78

**Comment by mikhailnathanielabordo** [comment]
Image PR: https://gitlab.com/hackernoon/creative/-/merge_requests/10

**Comment by atherdon** [comment]
@mikhailnathanielabordo both PRs merged - thank you!

**Comment by mikhailnathanielabordo** [comment]
Completed. https://github.com/atherdon/newsletters/pull/204
