### ISSUE TITLE
Particle #2

### ISSUE THREAD

**Issue by mikhailnathanielabordo** [atherdon/newsletters#205]
Folder: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/March/progressed/Particle2

empty content: https://github.com/atherdon/newsletters/tree/master/archive/Thematic/2021/March/progressed/Particle2/empty.html

images: https://gitlab.com/hackernoon/creative/-/tree/master/newsletters/memes/2021/03-March/08.03

Bitly Link: https://bit.ly/3aAy2Ff

AD Copy: Join 3,500 Developers at Spectra

AD Plug: Along the same note, a great thank to our sponsor, Particle. Particle is the edge-to-cloud IoT platform to help you connect the unconnected and unlock the promise of IoT. Join Hacker Noon and 3,500 developers at Spectra 2021, a one-day-only master class in IoT.

Logo: https://gitlab.com/hackernoon/creative/-/raw/master/newsletters/logos/thematic/2021/02-February/23.02/partcicle.png

cmpgn: https://www.noonifications.tech/send-to?i=1&c=79

**Comment by atherdon** [comment]
https://media4.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif

**Comment by mikhailnathanielabordo** [comment]
Gitlab Images: https://gitlab.com/hackernoon/creative/-/merge_requests/11
Email Template: https://github.com/atherdon/newsletters/pull/206

**Comment by atherdon** [comment]
merged

**Comment by mikhailnathanielabordo** [comment]
added bitly links. https://github.com/atherdon/newsletters/pull/207 cc: @atherdon
