### ISSUE TITLE
Particle #3

### ISSUE THREAD

**Issue by mikhailnathanielabordo** [atherdon/newsletters#212]
Folder: https://github.com/atherdon/newsletters/tree/master/NEW/2021/03-March/Particle#3

images:  https://creative-images-upld.s3.amazonaws.com/creative/newsletters/memes/2021/03-March/11.03

Bitly Link: https://bit.ly/3aAy2Ff

AD Copy: Join 3,500 Developers at Spectra

Logo: https://creative-images-upld.s3.amazonaws.com/creative/newsletters/logos/thematic/2021/02-February/23.02/partcicle.png

cmpgn: {Noonifications: Available if all html templates are ready}

**Comment by mikhailnathanielabordo** [comment]
I use the AWS S3 for images here.
also for Template still used the existing template. I tried using the full template but the images are distorted.

PR: https://github.com/atherdon/newsletters/pull/213

**Comment by atherdon** [comment]
@mikhailnathanielabordo tell me more about an issue with images.
even feel free to create a separate issue in markdown-generator repo and describe it in details there

**Comment by atherdon** [comment]
should we duplicate images into gitlab? or we can think about it later

**Comment by mikhailnathanielabordo** [comment]
> should we duplicate images into gitlab? or we can think about it later

I think we can just think about it later. we already have our s3 anyways. 🤷‍♂️ 

Also closing this. 🙇

**Comment by atherdon** [comment]
Ok, I'm planning some re-organization, so soon we'll have better workflow and it might save us some time
