### ISSUE TITLE
noonifications/2020 лого, которые пока нету

### ISSUE THREAD

**Issue by coder-do** [atherdon/newsletters#239]
February

http://docusaurus-newsletter.netlify.app/html/Noonifications/2020/February/The%20Noon%20Notification%20-%20Hackernoon%20SDR%20-%20Feb%2026.html

http://docusaurus-newsletter.netlify.app/html/Noonifications/2020/February/The%20Noon%20Notification%20-%20VP%20Sponsor%20-%20Feb%2010.html

http://docusaurus-newsletter.netlify.app/html/Noonifications/2020/February/The%20Noon%20Notification%20-%20Hackernoon%20SDR%20-%20Feb%2026.html

April:
---

http://docusaurus-newsletter.netlify.app/html/Noonifications/2020/May/Paragon%20May%2011.html

https://docusaurus-newsletter.netlify.app/html/noonifications/2020/april/facebook%20ama%20apr%2028

July:
https://docusaurus-newsletter.netlify.app/html/noonifications/2020/july/unstoppabledomains%20jul%2007

August:
https://docusaurus-newsletter.netlify.app/html/noonifications/2020/august/datascience%20salon%20aug%2004
https://docusaurus-newsletter.netlify.app/html/noonifications/2020/august/provectus%20aug%2010

Unsorted:
http://docusaurus-newsletter.netlify.app/html/Noonifications/2020/unsorted/The%20Noon%20Notification%20-%2007.html

https://docusaurus-newsletter.netlify.app/html/noonifications/2020/unsorted/the%20noon%20notification%20-%2002

**Comment by atherdon** [comment]
можете обновить инфу, какие лого нужны

**Comment by coder-do** [comment]
эти новые лого которые вы добавили исправлю в эмайлах - и обновлю

**Comment by coder-do** [comment]
обновил инфу пока что в noonifications/2020 этих не хватает

**Comment by atherdon** [comment]
@coder-do я добавил несколько логотипов

**Comment by coder-do** [comment]
обновил )
