### ISSUE TITLE
think about thematics structure and logos

### ISSUE THREAD

**Issue by coder-do** [atherdon/newsletters#251]
Мы пока что добавляем и фиксим только noonifications
В thematics у нас есть в сайдбаре All и там разбросано всё по месяцам 
* думаю можно распределить в сайдбаре там тоже по месяцам
* добавить в сайдбаре 2021 ( и там включить файлы из https://github.com/atherdon/newsletters/tree/master/OLD/archive/Thematic/2021)
* и фиксить лого которые у нас имеются в gitlab на данный момент

**Comment by atherdon** [comment]
конечно можно

**Comment by atherdon** [comment]
только файлы из 2021 перенести в newsletters-archive а потом оттуда уже делать перенос в html

**Comment by atherdon** [comment]
картинки и логотипы в thematics частично были исправлены. думаю для initial version - там меньше работы. плюс, с октября 2020 мы ж сразу начали картинки хранить на gitlab

**Comment by coder-do** [comment]
> только файлы из 2021 перенести в newsletters-archive а потом оттуда уже делать перенос в html

в гитлабе уже добавил я в пошлом PR

**Comment by atherdon** [comment]
ок
