### ISSUE TITLE
include fun gif

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#263]
like a link to our gipfy and also an image small version: https://giphy.com/stickers/hackernoon-hacker-noon-iG9qDbeYfrCYFqQ2OV

**Comment by coder-do** [comment]
эти гифы куда мне добавить? можете страницы указать либо просто подксказать где вы их представляете чтоб были?

**Comment by atherdon** [comment]
я думал как минимум в хеадере футере на основном сайте сделать, чтобы было понятна связь этого архива с основным сайтом
