### ISSUE TITLE
Mysterium #5

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#278]
Folder: https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/Mysteruim5

images: https://creative-images-upld.s3.amazonaws.com/creative/

Bitly Link: https://bit.ly/3dLeRud

AD Copy: Move $MYST to Polygon for FREE (+ Rewards)

Logo: {gitlab /logo/ folder}

cmpgn: {Noonifications: Available if all html templates are ready}

[[DRAFT] Mysterium x Hacker Noon Newsletter - Crypto & Passive Income.pdf](https://github.com/atherdon/newsletters/files/6286609/DRAFT.Mysterium.x.Hacker.Noon.Newsletter.-.Crypto.Passive.Income.pdf)

**Comment by atherdon** [comment]
На примере этой campaign можно как раз попробывать чтобы вы сгенерировали темлплейт и залить картинки на amazon s3

**Comment by atherdon** [comment]
не учавствовал 3 недели рассылке и все перепуталось. завтра наверное разгребусь и создам еще задач.
поидее мы сразу сможем сделать 4-5 темплейтов, потому что контент уже давно был готов

**Comment by F1reMonster** [comment]
готово

PS: посилання на зображення якісь будуть? Є тільки на перше в твітер, на інші в пдфі немає

**Comment by atherdon** [comment]
я поставил просто ссылки на теги на сайте.
в будущем попробую не пропускать это, сорри

>

**Comment by atherdon** [comment]
перенес в sendy для отправки - спасибо!
