### ISSUE TITLE
Podcasts export.

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#282]
Podcasts export.

мы скопировали контент с сайта подкастов.

я залил это все в один большой файл, но думаю что нужно разбить все эпизоды пофайлово.

https://github.com/atherdon/newsletters/blob/master/website/docs/podcasts/loooong-file.md

я бы брал такую структуру 
 год \ месяц - а название файла - E%number%-%title%.md

у каждого md файла унжно делать стандартную для докузавруса щапку, чтобы проще было вытаскивать информацию

**Comment by atherdon** [comment]
cc @coder-do

**Comment by coder-do** [comment]
в этих подкастах фото, гифы, лого hn - такого нету как понял , просто md файлами сделать и всё

**Comment by atherdon** [comment]
можете уточнить что вы имеете ввиду? до конца не понял

**Comment by atherdon** [comment]
пока что там только текст\ссылки.
скорее всего просто нету возможности на podbean добавлять другой тип контента.
вначале сделаем такую версию а уже потом будем думать

**Comment by coder-do** [comment]
Этот таск законили 
@atherdon

**Comment by coder-do** [comment]
Тот большой файл подкастов куда то в архивы либо в _old папки нужно добавить? или убрать вообще?

**Comment by atherdon** [comment]
> Тот большой файл подкастов куда то в архивы либо в _old папки нужно добавить? или убрать вообще?

думаю мы просто удаляем тот файл.

таск закрываю
