### ISSUE TITLE
FreeTonWC

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#287]
Folder: https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/FreeTonWC

images: https://creative-images-upld.s3.amazonaws.com/creative/

we wouldn't use any sponsor logo / ad message
something similar to https://www.noonifications.tech/w/892w09DfPyOfe4cAgQZrmd2A

cmpgn: {Noonifications: Available if all html templates are ready}

**Comment by atherdon** [comment]
[Untitled document (1).pdf](https://github.com/atherdon/newsletters/files/6292306/Untitled.document.1.pdf)

**Comment by atherdon** [comment]
@F1reMonster мы можем еще эту рассылку подготовить

**Comment by F1reMonster** [comment]
> @F1reMonster мы можем еще эту рассылку подготовить

зробив

PS: немає посилань на зображення, і також чекаю на рекламні матеріали

**Comment by atherdon** [comment]
у нас для этой рассылки не будет спонсора - можно удалить блок сверху и снизу.
будет выглядеть похоже на эту campaign: https://www.noonifications.tech/w/892w09DfPyOfe4cAgQZrmd2A

**Comment by atherdon** [comment]
посмотрю сейчас насчет ссылок к картинкам

**Comment by atherdon** [comment]
ссылки:
1. https://hackernoon.com/decentralized-internet-writing-contest
2. https://app.hackernoon.com/new
3. https://hackernoon.com/tagged/decentralized-internet

**Comment by atherdon** [comment]
нашел что ссылки опять стали приклеиваться изза генератора

![image](https://user-images.githubusercontent.com/1469198/114432943-e9e89e00-9bc9-11eb-9bde-897df394ea34.png)

---

![image](https://user-images.githubusercontent.com/1469198/114433001-f8cf5080-9bc9-11eb-81a2-0301e387ad1f.png)

---

![image](https://user-images.githubusercontent.com/1469198/114433059-0b498a00-9bca-11eb-84bc-2a3a951b70c2.png)

---

![image](https://user-images.githubusercontent.com/1469198/114433109-1ac8d300-9bca-11eb-8fee-8e9e26fcfd7f.png)

**Comment by F1reMonster** [comment]
поправив

**Comment by atherdon** [comment]
только сейчас смог посмотреть - title и preview идут со старого темплейта, со stackoverflow1 cc @F1reMonster

**Comment by F1reMonster** [comment]
Зараз гляну

**Comment by F1reMonster** [comment]
> только сейчас смог посмотреть - title и preview идут со старого темплейта, со stackoverflow1 cc @F1reMonster

поправив, і завантажив
