### ISSUE TITLE
add a link to freetonWC

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#304]
"Join our writing contest and get a chance to win cool prizes".
https://hackernoon.com/the-decentralized-internet-writing-contest-fq1i35t4

![image](https://user-images.githubusercontent.com/1469198/115144208-1120ee80-a054-11eb-8ff0-b4cf03287521.png)

**Comment by atherdon** [comment]
предлагаю добавить в те emails, которые мы сейчас делаем
- https://github.com/atherdon/newsletters/blob/master/campaigns/archive/Thematic/2021/April/stackoverflow2/template.html
- https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/Soda.io1
- https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/couchdb%232
- https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/launchdarkly4
- https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/jfrog1

**Comment by F1reMonster** [comment]
готово
