### ISSUE TITLE
move out this content 

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#315]
here: https://gitlab.com/hackernoon/creative/-/tree/master/newsletters

and then delete it from this repo. @coder-do

**Comment by coder-do** [comment]
и куда вывести контент - или просто убрать и все?

**Comment by atherdon** [comment]
сюда вынести: https://gitlab.com/hackernoon/creative/-/tree/master/newsletters

**Comment by coder-do** [comment]
а ) контент этого репозитория вынести в https://gitlab.com/hackernoon/creative/-/tree/master/newsletters ?

**Comment by atherdon** [comment]
стоп - я запутался сам.

**Comment by atherdon** [comment]
Я затупил или несохранился комментарий :)

мы выносим архив с md файлами из этого репозитория: https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/md-for-generator

переносим в https://gitlab.com/hackernoon/creative/-/tree/master/newsletters

сорри @coder-do

**Comment by coder-do** [comment]
бывает) просто я подумал опять сам себе затрудняю таск :))
https://gitlab.com/hackernoon/creative/-/merge_requests/12

**Comment by atherdon** [comment]
вроде готово
