### ISSUE TITLE
mysterium 4(6)

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#317]
Folder: https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April/Mysterium4(6)

images: https://creative-images-upld.s3.amazonaws.com/creative/

Bitly Link: https://bit.ly/3g9XSo8

AD Copy: Download Mysterium crypto VPN - First 20 GB streaming FREE

Logo: https://creative-images-upld.s3.amazonaws.com/creative/newsletters/memes/2021/04-April/09-04/image2.png

cmpgn: https://www.noonifications.tech/send-to?i=1&c=98

**Comment by atherdon** [comment]
[Uploading Mysterium_content.pdf…]()

**Comment by atherdon** [comment]
[Mysterium_content.pdf](https://github.com/atherdon/newsletters/files/6359112/Mysterium_content.pdf)

**Comment by atherdon** [comment]
добавил ad materials

**Comment by F1reMonster** [comment]
готово

**Comment by atherdon** [comment]
они опять забыли добавить ссылки для картинок :facepalm: 

- https://hackernoon.com/tagged/netflix
- https://hackernoon.com/tagged/passwords
- https://hackernoon.com/search?query=security
- https://hackernoon.com/search?query=vpn

**Comment by atherdon** [comment]
выложено
