### ISSUE TITLE
footer social icons

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#320]
помойму в одном из прошлых писем 2 иконки крешились
хочу залить их на наш s3 в какую то папку, чтобы точно работали.
сейчас картинки у нас все еще ссылаются на mailchimp.

Плюс, можете в этот таск скинуть urls этих картинок, чтобы я поменял путь в генераторе темлпейтов

картинки лежат в https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/April

и мы получается должны будем изменить темплейты:
- Soda
- Launchdarkly4
- Launchdarkly5
- Mysterium4

**Comment by F1reMonster** [comment]
facebook - https://creative-images-upld.s3.amazonaws.com/creative/newsletters/icons/facebook.png
email - https://creative-images-upld.s3.amazonaws.com/creative/newsletters/icons/forwardtofriend.png
instagram - https://creative-images-upld.s3.amazonaws.com/creative/newsletters/icons/instagram.png
link - https://creative-images-upld.s3.amazonaws.com/creative/newsletters/icons/link.png
twitter - https://creative-images-upld.s3.amazonaws.com/creative/newsletters/icons/twitter.png
youtube - https://creative-images-upld.s3.amazonaws.com/creative/newsletters/icons/youtube.png

**Comment by atherdon** [comment]
спасибо

**Comment by atherdon** [comment]
готово и перенесено в генератор
