### ISSUE TITLE
lets move out March folder

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#333]
cc @coder-do 

https://github.com/atherdon/newsletters/tree/master/campaigns/archive/Thematic/2021/March

**Comment by atherdon** [comment]
@coder-do we can do this task if you have time.
I'll also clean up April soon

**Comment by coder-do** [comment]
> I'll also clean up April soon

Мы это еще в докусаурус не добавляли - последним был март месяц

**Comment by atherdon** [comment]
@coder-do думаю можно и апрель переносить. Единственное что я заметил - у нас кампании могут идти в разнобой - потому что даты я забыл ставить. но наверное с этим мы потом разберемся

**Comment by atherdon** [comment]
@coder-do i'm fine to move out an April folder as well
