### ISSUE TITLE
images/logos clean up

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#349]
does docusasurus display any image from GitHub?
it should be something similar too `https://raw.githubusercontent.com/atherdon/newsletters/master/campaigns/archive/logos/thematic/2020/Vettery.png`

cc @coder-do

**Comment by coder-do** [comment]
@atherdon да , я вставил эту картинку и вроде открыл проблем не было

**Comment by atherdon** [comment]
я имею ввиду что мне кажется что часть картинок из старых кампаний, например 2020 года может ссылаться на гитхаб - на этот репозиторий. можете сделать поиск по проекту и сказать сколько таких картинок имеется? я просто хотел удалить папку `https://github.com/atherdon/newsletters/tree/master/campaigns/archive/img` но мне кажется что я могу чтото покрешить

**Comment by coder-do** [comment]
вроде из папки `img` ничего не нашлось - но из папки `logos` (рядом с img) были несколько логотипов - это было всё что нашел

**Comment by coder-do** [comment]
мне апрель месяц в докусаурус добавлять уже ?

**Comment by atherdon** [comment]
@coder-do https://github.com/atherdon/newsletters/tree/master/campaigns/archive/WIP/April

да, апрель можно закидывать везде. 

тогда img я удаляю. можем ли мы заменить logos(нужно просто проверить их наличие в S3)?

**Comment by coder-do** [comment]
>  можем ли мы заменить logos(нужно просто проверить их наличие в S3)?

даб я перечислю эти картинки (они все в май месяце эти лого) - если они есть в  S3, можем заменить

https://github.com/atherdon/newsletters/blob/29fa188d4fc70e039b67f5f9a5c1261d5732a93f/campaigns/archive/WIP/May/00-debt/badges-broken-lazy-to-fix/template.html#L457

https://github.com/atherdon/newsletters/blob/29fa188d4fc70e039b67f5f9a5c1261d5732a93f/campaigns/archive/WIP/May/00-debt/Udemy/template.html#L457

https://github.com/atherdon/newsletters/blob/29fa188d4fc70e039b67f5f9a5c1261d5732a93f/campaigns/archive/WIP/May/00-debt/Udemy-2/template.html#L457

https://github.com/atherdon/newsletters/blob/29fa188d4fc70e039b67f5f9a5c1261d5732a93f/campaigns/archive/WIP/May/00-debt/unstoppable%20domains/template.html#L457

Вроде лого одинаковы ) если есть дайте ссылку на лого можем заменить потом

**Comment by atherdon** [comment]
@coder-do все просто: https://creative-images-upld.s3.amazonaws.com/creative/newsletters/logos/thematic/2020/October/Bridgecrew_stacked.jpg

**Comment by coder-do** [comment]
поправил )

**Comment by atherdon** [comment]
закрываю

**Comment by atherdon** [comment]
спасибо
