### ISSUE TITLE
hack-earth

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#399]
Folder: https://github.com/atherdon/newsletters/tree/master/campaigns/WIP/June/hackerEarth

images: https://creative-images-upld.s3.amazonaws.com/creative/

Bitly Link: https://bit.ly/3z8ufdY

AD Copy: Your first step to coding enlightenment

Logo: {gitlab /logo/ folder}

cmpgn: {Noonifications: Available if all html templates are ready}

**Comment by atherdon** [comment]
сейчас залью новое лого и ad materials

**Comment by atherdon** [comment]
![image](https://user-images.githubusercontent.com/1469198/121173634-b5a7fb80-c861-11eb-99f9-2c5ebb6675ff.png)
сюда тоже нужно будет добавить ссылок

**Comment by atherdon** [comment]
нужно добавить bitly в еще двух местах @coder-do 

![image](https://user-images.githubusercontent.com/1469198/121218719-a8a00200-c88b-11eb-8135-dc49146b1687.png)

**Comment by atherdon** [comment]
еще одна ссылка
![image](https://user-images.githubusercontent.com/1469198/121219029-f61c6f00-c88b-11eb-967f-329a93a13bc2.png)

**Comment by coder-do** [comment]
готово

**Comment by atherdon** [comment]
проверьте превью

и нужно поправить 

![image](https://user-images.githubusercontent.com/1469198/121346358-af338580-c92e-11eb-8bee-8fdf7b472d35.png)


у нас там CodeMonk

**Comment by atherdon** [comment]
completed
