### ISSUE TITLE
create first template by hands, using content from a document

### ISSUE THREAD

**Issue by atherdon** [atherdon/newsletters#5]
So, we'll have the next version of simple message. 
template to catch as inspiration: thematics/2020/august/ Partners
doc: 2020/september/in-process/partners/content.pdf

So, the main wrapper is here:

```

<div dir="ltr" style="text-align: justify;"><span style="font-size:15px"><span style="font-family:trebuchet ms,lucida grande,lucida sans unicode,lucida sans,tahoma,sans-serif">XXX</span></span></div>

```

**Comment by atherdon** [comment]
buzz me for more details - i'll shoot a video for U

**Comment by eternal-web** [comment]
I watched the video, the beginning is easy, the question is on github I know pull and push can pull the repository and push a new index

I am learning English and understand it without a translator, but for communication I will use translation at first

**Comment by eternal-web** [comment]
I will use translation at first time

**Comment by atherdon** [comment]
ok, not a problem. let's have a practice.

**Comment by atherdon** [comment]
@eternal-web tell me if you need help with that

**Comment by eternal-web** [comment]
I to the end work on this task

**Comment by atherdon** [comment]
I don't think so :)

#9
